/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.melissadata;

public class mdIpLocatorJavaWrapperJNI {
static{
try{ System.loadLibrary("mdIpLocatorJavaWrapper");}
catch(UnsatisfiedLinkError ule){
System.out.println(ule);
System.out.println("java.library.path = " + System.getProperty("java.library.path"));}}
  public final static native int mdIpLocator_ErrorNone_get();
  public final static native int mdIpLocator_Local_get();
  public final static native int mdIpLocator_Auto_get();
  public final static native int mdIpLocator_FCM_LTR_AUTO_NONAUTO_get();
  public final static native int mdIpLocator_FCM_POSTCARD_AUTO_NONAUTO_get();
  public final static native int mdIpLocator_FCM_FLAT_COTRAY_get();
  public final static native int mdIpLocator_STD_LTR_ECRRT_AUTO_NONAUTO_get();
  public final static native int mdIpLocator_STD_FLAT_ECRRT_COSACK_get();
  public final static native int mdIpLocator_RESIDUALS_LEFT_get();
  public final static native long new_mdIpLocator();
  public final static native void delete_mdIpLocator(long jarg1);
  public final static native int mdIpLocator_InitializeDataFiles(long jarg1, mdIpLocator jarg1_);
  public final static native void mdIpLocator_SetPathToIpLocatorFiles(long jarg1, mdIpLocator jarg1_, String jarg2);
  public final static native String mdIpLocator_GetInitializeErrorString(long jarg1, mdIpLocator jarg1_);
  public final static native boolean mdIpLocator_SetLicenseString(long jarg1, mdIpLocator jarg1_, String jarg2);
  public final static native String mdIpLocator_GetBuildNumber(long jarg1, mdIpLocator jarg1_);
  public final static native String mdIpLocator_GetDatabaseDate(long jarg1, mdIpLocator jarg1_);
  public final static native String mdIpLocator_GetDatabaseExpirationDate(long jarg1, mdIpLocator jarg1_);
  public final static native String mdIpLocator_GetLicenseStringExpirationDate(long jarg1, mdIpLocator jarg1_);
  public final static native boolean mdIpLocator_LocateIpAddress(long jarg1, mdIpLocator jarg1_, String jarg2);
  public final static native String mdIpLocator_GetCity(long jarg1, mdIpLocator jarg1_);
  public final static native String mdIpLocator_GetCountry(long jarg1, mdIpLocator jarg1_);
  public final static native String mdIpLocator_GetCountryAbbreviation(long jarg1, mdIpLocator jarg1_);
  public final static native String mdIpLocator_GetDomainName(long jarg1, mdIpLocator jarg1_);
  public final static native String mdIpLocator_GetISP(long jarg1, mdIpLocator jarg1_);
  public final static native String mdIpLocator_GetLongitude(long jarg1, mdIpLocator jarg1_);
  public final static native String mdIpLocator_GetLatitude(long jarg1, mdIpLocator jarg1_);
  public final static native String mdIpLocator_GetRegion(long jarg1, mdIpLocator jarg1_);
  public final static native String mdIpLocator_GetZip(long jarg1, mdIpLocator jarg1_);
  public final static native String mdIpLocator_GetResults(long jarg1, mdIpLocator jarg1_);
}
