default[:melissadata][:paths][:root_dir]        = "/opt/melissadata"
default[:melissadata][:paths][:config_file]     = "/opt/melissadata/config.yml"
default[:melissadata][:paths][:license_file]    = "/opt/melissadata/license.txt"
default[:melissadata][:paths][:log_dir]         = "/var/log/melissadata"
default[:melissadata][:runner_user]             = "vagrant"
