DIR=/opt/melissadata/lib
RUBYDIR=<%= node[:languages][:ruby][:gems_dir].gsub('gems/', '') %>/<%= node[:languages][:ruby][:platform] %>
CXX=g++
LDLIBS=-L$(DIR) -Wl,-rpath,$(DIR)
FLAGS=-g -O -Wall -pthread -m64
CXXFLAGS=$(FLAGS) -fpic -c $(LDLIBS) -I$(DIR) -I$(RUBYDIR)
LDFLAGS=$(COMMONFLAGS) $(LDLIBS)

all: Addr Email Geo IpLocator Name Phone

Addr: mdAddrRubyWrapper.cpp mdAddr.h mdEnums.h
	$(CXX) $(CXXFLAGS) mdAddrRubyWrapper.cpp
	$(CXX) $(LDFLAGS) -lmdAddr -shared mdAddrRubyWrapper.o -o $(DIR)/mdAddrRubyWrapper.so
	$(RM) mdAddrRubyWrapper.o

Email: mdEmailRubyWrapper.cpp mdEmail.h mdEnums.h
	$(CXX) $(CXXFLAGS) mdEmailRubyWrapper.cpp
	$(CXX) $(LDFLAGS) -lmdEmail -shared mdEmailRubyWrapper.o -o $(DIR)/mdEmailRubyWrapper.so
	$(RM) mdEmailRubyWrapper.o

Geo: mdGeoRubyWrapper.cpp mdGeo.h mdEnums.h
	$(CXX) $(CXXFLAGS) mdGeoRubyWrapper.cpp
	$(CXX) $(LDFLAGS) -lmdGeo -shared mdGeoRubyWrapper.o -o $(DIR)/mdGeoRubyWrapper.so
	$(RM) mdGeoRubyWrapper.o

IpLocator: mdIpLocatorRubyWrapper.cpp mdIpLocator.h mdEnums.h
	$(CXX) $(CXXFLAGS) mdIpLocatorRubyWrapper.cpp
	$(CXX) $(LDFLAGS) -lmdIpLocator -shared mdIpLocatorRubyWrapper.o -o $(DIR)/mdIpLocatorRubyWrapper.so
	$(RM) mdIpLocatorRubyWrapper.o

Name: mdNameRubyWrapper.cpp mdName.h mdEnums.h
	$(CXX) $(CXXFLAGS) mdNameRubyWrapper.cpp
	$(CXX) $(LDFLAGS) -lmdName -shared mdNameRubyWrapper.o -o $(DIR)/mdNameRubyWrapper.so
	$(RM) mdNameRubyWrapper.o

Phone: mdPhoneRubyWrapper.cpp mdPhone.h mdEnums.h
	$(CXX) $(CXXFLAGS) mdPhoneRubyWrapper.cpp
	$(CXX) $(LDFLAGS) -lmdPhone -shared mdPhoneRubyWrapper.o -o $(DIR)/mdPhoneRubyWrapper.so
	$(RM) mdPhoneRubyWrapper.o
