/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef PHP_MDIPLOCATORPHPWRAPPER_H
#define PHP_MDIPLOCATORPHPWRAPPER_H

extern zend_module_entry mdIpLocatorPHPWrapper_module_entry;
#define phpext_mdIpLocatorPHPWrapper_ptr &mdIpLocatorPHPWrapper_module_entry

#ifdef PHP_WIN32
# define PHP_MDIPLOCATORPHPWRAPPER_API __declspec(dllexport)
#else
# define PHP_MDIPLOCATORPHPWRAPPER_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(mdIpLocatorPHPWrapper);
PHP_MSHUTDOWN_FUNCTION(mdIpLocatorPHPWrapper);
PHP_RINIT_FUNCTION(mdIpLocatorPHPWrapper);
PHP_RSHUTDOWN_FUNCTION(mdIpLocatorPHPWrapper);
PHP_MINFO_FUNCTION(mdIpLocatorPHPWrapper);

ZEND_NAMED_FUNCTION(_wrap_new_mdIpLocator);
ZEND_NAMED_FUNCTION(_wrap_mdIpLocator_InitializeDataFiles);
ZEND_NAMED_FUNCTION(_wrap_mdIpLocator_SetPathToIpLocatorFiles);
ZEND_NAMED_FUNCTION(_wrap_mdIpLocator_GetInitializeErrorString);
ZEND_NAMED_FUNCTION(_wrap_mdIpLocator_SetLicenseString);
ZEND_NAMED_FUNCTION(_wrap_mdIpLocator_GetBuildNumber);
ZEND_NAMED_FUNCTION(_wrap_mdIpLocator_GetDatabaseDate);
ZEND_NAMED_FUNCTION(_wrap_mdIpLocator_GetDatabaseExpirationDate);
ZEND_NAMED_FUNCTION(_wrap_mdIpLocator_GetLicenseStringExpirationDate);
ZEND_NAMED_FUNCTION(_wrap_mdIpLocator_LocateIpAddress);
ZEND_NAMED_FUNCTION(_wrap_mdIpLocator_GetCity);
ZEND_NAMED_FUNCTION(_wrap_mdIpLocator_GetCountry);
ZEND_NAMED_FUNCTION(_wrap_mdIpLocator_GetCountryAbbreviation);
ZEND_NAMED_FUNCTION(_wrap_mdIpLocator_GetDomainName);
ZEND_NAMED_FUNCTION(_wrap_mdIpLocator_GetISP);
ZEND_NAMED_FUNCTION(_wrap_mdIpLocator_GetLongitude);
ZEND_NAMED_FUNCTION(_wrap_mdIpLocator_GetLatitude);
ZEND_NAMED_FUNCTION(_wrap_mdIpLocator_GetRegion);
ZEND_NAMED_FUNCTION(_wrap_mdIpLocator_GetZip);
ZEND_NAMED_FUNCTION(_wrap_mdIpLocator_GetResults);
#endif /* PHP_MDIPLOCATORPHPWRAPPER_H */
