/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "mdIpLocator.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1ErrorNone_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  mdIpLocator::ProgramStatus result;
  
  (void)jenv;
  (void)jcls;
  result = (mdIpLocator::ProgramStatus)mdIpLocator::ErrorNone;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1Local_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  mdIpLocator::AccessType result;
  
  (void)jenv;
  (void)jcls;
  result = (mdIpLocator::AccessType)mdIpLocator::Local;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1Auto_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  mdIpLocator::DiacriticsMode result;
  
  (void)jenv;
  (void)jcls;
  result = (mdIpLocator::DiacriticsMode)mdIpLocator::Auto;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1FCM_1LTR_1AUTO_1NONAUTO_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  mdIpLocator::SortationCode result;
  
  (void)jenv;
  (void)jcls;
  result = (mdIpLocator::SortationCode)mdIpLocator::FCM_LTR_AUTO_NONAUTO;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1FCM_1POSTCARD_1AUTO_1NONAUTO_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  mdIpLocator::SortationCode result;
  
  (void)jenv;
  (void)jcls;
  result = (mdIpLocator::SortationCode)mdIpLocator::FCM_POSTCARD_AUTO_NONAUTO;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1FCM_1FLAT_1COTRAY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  mdIpLocator::SortationCode result;
  
  (void)jenv;
  (void)jcls;
  result = (mdIpLocator::SortationCode)mdIpLocator::FCM_FLAT_COTRAY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1STD_1LTR_1ECRRT_1AUTO_1NONAUTO_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  mdIpLocator::SortationCode result;
  
  (void)jenv;
  (void)jcls;
  result = (mdIpLocator::SortationCode)mdIpLocator::STD_LTR_ECRRT_AUTO_NONAUTO;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1STD_1FLAT_1ECRRT_1COSACK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  mdIpLocator::SortationCode result;
  
  (void)jenv;
  (void)jcls;
  result = (mdIpLocator::SortationCode)mdIpLocator::STD_FLAT_ECRRT_COSACK;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1RESIDUALS_1LEFT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  mdIpLocator::SortationCode result;
  
  (void)jenv;
  (void)jcls;
  result = (mdIpLocator::SortationCode)mdIpLocator::RESIDUALS_LEFT;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_new_1mdIpLocator(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  mdIpLocator *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (mdIpLocator *)new mdIpLocator();
  *(mdIpLocator **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_delete_1mdIpLocator(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  mdIpLocator *arg1 = (mdIpLocator *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(mdIpLocator **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jint JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1InitializeDataFiles(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  mdIpLocator *arg1 = (mdIpLocator *) 0 ;
  enum mdIpLocator::ProgramStatus result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(mdIpLocator **)&jarg1; 
  result = (enum mdIpLocator::ProgramStatus)(arg1)->InitializeDataFiles();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1SetPathToIpLocatorFiles(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  mdIpLocator *arg1 = (mdIpLocator *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(mdIpLocator **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return ;
  }
  (arg1)->SetPathToIpLocatorFiles((char const *)arg2);
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1GetInitializeErrorString(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  mdIpLocator *arg1 = (mdIpLocator *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(mdIpLocator **)&jarg1; 
  result = (char *)(arg1)->GetInitializeErrorString();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1SetLicenseString(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jboolean jresult = 0 ;
  mdIpLocator *arg1 = (mdIpLocator *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(mdIpLocator **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return 0;
  }
  result = (bool)(arg1)->SetLicenseString((char const *)arg2);
  jresult = (jboolean)result; 
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1GetBuildNumber(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  mdIpLocator *arg1 = (mdIpLocator *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(mdIpLocator **)&jarg1; 
  result = (char *)(arg1)->GetBuildNumber();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1GetDatabaseDate(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  mdIpLocator *arg1 = (mdIpLocator *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(mdIpLocator **)&jarg1; 
  result = (char *)(arg1)->GetDatabaseDate();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1GetDatabaseExpirationDate(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  mdIpLocator *arg1 = (mdIpLocator *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(mdIpLocator **)&jarg1; 
  result = (char *)(arg1)->GetDatabaseExpirationDate();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1GetLicenseStringExpirationDate(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  mdIpLocator *arg1 = (mdIpLocator *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(mdIpLocator **)&jarg1; 
  result = (char *)(arg1)->GetLicenseStringExpirationDate();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1LocateIpAddress(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jboolean jresult = 0 ;
  mdIpLocator *arg1 = (mdIpLocator *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(mdIpLocator **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return 0;
  }
  result = (bool)(arg1)->LocateIpAddress((char const *)arg2);
  jresult = (jboolean)result; 
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1GetCity(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  mdIpLocator *arg1 = (mdIpLocator *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(mdIpLocator **)&jarg1; 
  result = (char *)(arg1)->GetCity();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1GetCountry(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  mdIpLocator *arg1 = (mdIpLocator *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(mdIpLocator **)&jarg1; 
  result = (char *)(arg1)->GetCountry();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1GetCountryAbbreviation(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  mdIpLocator *arg1 = (mdIpLocator *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(mdIpLocator **)&jarg1; 
  result = (char *)(arg1)->GetCountryAbbreviation();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1GetDomainName(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  mdIpLocator *arg1 = (mdIpLocator *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(mdIpLocator **)&jarg1; 
  result = (char *)(arg1)->GetDomainName();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1GetISP(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  mdIpLocator *arg1 = (mdIpLocator *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(mdIpLocator **)&jarg1; 
  result = (char *)(arg1)->GetISP();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1GetLongitude(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  mdIpLocator *arg1 = (mdIpLocator *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(mdIpLocator **)&jarg1; 
  result = (char *)(arg1)->GetLongitude();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1GetLatitude(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  mdIpLocator *arg1 = (mdIpLocator *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(mdIpLocator **)&jarg1; 
  result = (char *)(arg1)->GetLatitude();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1GetRegion(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  mdIpLocator *arg1 = (mdIpLocator *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(mdIpLocator **)&jarg1; 
  result = (char *)(arg1)->GetRegion();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1GetZip(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  mdIpLocator *arg1 = (mdIpLocator *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(mdIpLocator **)&jarg1; 
  result = (char *)(arg1)->GetZip();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_melissadata_mdIpLocatorJavaWrapperJNI_mdIpLocator_1GetResults(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  mdIpLocator *arg1 = (mdIpLocator *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(mdIpLocator **)&jarg1; 
  result = (char *)(arg1)->GetResults();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


#ifdef __cplusplus
}
#endif

